language: generic
sudo: required
services:
  - docker

# leafsolutions/docker-react follows the convention:
# image tag = {username}/{project name}:{optional:tag}
before_install:
  - docker build -t leafsolutions/docker-react -f Dockerfile.dev .
# CI=true
# https://create-react-app.dev/docs/running-tests/#linux-macos-bash
script:
  - docker run -e CI=true leafsolutions/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-react-sample'
  env: 'Dockerreactsample-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-874803167750'
  bucket_path: 'docker-react-sample'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
